### ISSUE TITLE
Why are there no issues?

### ISSUE THREAD

**Issue by a-alhusaini** [edhowland/viper#4]
Do you guys use a seperate issue tracker?

**Comment by edhowland** [comment]
Ok, this is the situation. Effectively, because I am newly blind, I strugle with
with most web forum software which includes GitHub issues. So since I had a MVP
version of Viper I have been tracking issues in the file Bugs.md in this repo.
The file is split into 2 parts with heading level 1s starting with 
Todo (60 items)  and then Bugs (45 items).
You are the first person who has shown any interest in this project beyond idle
curiosity. Mainly, I have been living in this  deserted dev island for a while
now.  I need to get back to active development here.
I am working towards a 2.1 release and almost reached the 2.0.13 milestone.
What is your situation? Can I be of any help?

I think my email is on GitHub in my profile. If not, then it is easy to guess:
My: <first.last>@<mail provided by big search engine>.com
You can reach me there or on
Mastodon on @edhowland@fosstodon.org.
Or continue on this thread, if you prefer.

**Comment by edhowland** [comment]
Work has switched over to Viper3. This is a complete rewrite in Nushell to make things greatly simplified. Work on Viper2 is currently suspended. I have not yet created the Viper3 repository yet.
